### PR TITLE
Add a CLA checking bot

### PR DESCRIPTION
**Pull request by hgtonight**
This adds a basic github client bot per the issue #15.

I have tested it as working against a repo here: https://github.com/hgtonight/cla_webhook_testing

Opening a new PR against that repository will exercise this code.

[x] Verifies webhook signature via specified shared secret
[x] Handles Pull Request webhook at `https://forums.example.com/contributors/pullrequest`
[x] Looks up GitHub username in the local user model
[x] Checks the users 'DateContributorAgreement' field for non-null value
[x] Comments on the pull request via specified OAuth token

Future enhancement:
[ ] Looks for GitHub username in profile
[ ] Provide settings screen to edit the new configs

### CODE REVIEW

**Comment by linc** [comment]
Can you give me some background on where all this code is coming from? Did you pull in some third-party project?

**Comment by hgtonight** [comment]
Sorry about that. I used the first PHP library here: https://developer.github.com/libraries/

The project is pulled from: https://github.com/tan-tan-kanarek/github-php-client

I couldn't figure out how to get composer to work for sub projects, but the project is on packagist: https://packagist.org/packages/tan-tan-kanarek/github-php-client

**Comment by initvector** [comment]
You can make a lightweight GitHub API client with [Garden HTTP](https://github.com/vanilla/garden-http). There's even an example GitHub client in the project's README.  The library is already required in Vanilla, so there are no additional dependencies.

**Comment by hgtonight** [comment]
@initvector That looks like a good idea.

I used the github library only for the comment posting, so it should be relatively easy to swap out for Garden HTTP.

**Comment by linc** [comment]
I also want to point out that @tburry just did a trial integration with CLA Assistant here: https://github.com/vanilla/garden-http/pull/11 (speaking of that repo). It would require everyone to re-sign the CLA via their system, but it might be simpler than reworking this if we wanna let tem handle it, and it integrates with the checks on GitHub (click "View Details" on that PR).

Kinda weird that both of you suddenly worked on this at the same time; I'm neutral on which approach to take. On one hand, I don't think signing the CLA in a new spot is a big hurdle and it's more robust that our current same-username approach. On the other, I like building on what we have.

**Comment by hgtonight** [comment]
Yeah, I finally have some time to dedicate to this and I pick a bot because I haven't really written one before. Not even an hour after my PR is submitted I get a notification from a 'CLA-Assistant'.

I chuckled.

I will look into the Garden HTTP later tonight.

**Comment by hgtonight** [comment]
I have updated this PR to not use a third party library.

Thanks for the info @initvector, the Garden HTTP client was great to use.

**Comment by linc** [comment]
I really appreciate the effort here, but I think I'm gonna take a pass on this since Todd put it onto the core repo another way. I don't wanna start mixing and matching CLA checkers, and the other one doesn't require endpoints on the community which I appreciate from a security perspective.

**Comment by hgtonight** [comment]
No problem. I learned a lot doing this, so at least I got that going for me.

🤓

**Pull request closed without merging**
