### PR TITLE
Add community confidence rating to addons

### PR DESCRIPTION
**Pull request by hgtonight**
This adds a community confidence rating to addons.

It is a work in progress.

* [x] Detect Vanilla (core) versions
* [x] Display community rating of plugins in addon page
* [ ] Display current community rating in addons list
* [x] Thumb up/down voting
* [ ] View past confidence level for core versions
* [ ] Denormalized data for recent core versions

### CODE REVIEW

**Comment by hgtonight** [comment]
Will fix issue #6 when done.

**Comment by linc** [comment]
OK. Could you do high-level bullet points in the PR description of what all is being done here when you're done? Maybe so checkboxes to indicate what's left?

```
* [ ] Doing a checkbox in Markdown
```

Please docblock everything fo' sho', and remember camelCase for all function/method calls too. 

Thanks for taking this on!

**Comment by hgtonight** [comment]
I will fix the casing on the new methods.

**Comment by linc** [comment]
Hey Zach, do you still intend to keep working here or should we close this for now? We're missing all docs here and a merge conflict has developed. Also wanna apply our new coding standards to this app soon, so I wanna either clear this for a merge or archive it for reference & revisit after that.

**Comment by hgtonight** [comment]
Archive it. I will hopefully revisit it soon.

**Comment by linc** [comment]
OK, thanks! Appreciate the work. Hopefully you won't be working alone on this repo much longer.

**Pull request closed without merging**
